name: CI/CD2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o main -v ./...

      - name: Run the app
        run: ./main &

      - name: Run functional tests
        uses: matt-ball/newman-action@master
        with:
          collection: test/postman-tests.json